### PR TITLE
fix: remap symbolic links to guest paths to corresponding host paths.

### LINKED ISSUE #580: Task outputs that are symlinks to inputs do not work
**Describe the bug**

Create a `repro.wdl` with the following contents:

```wdl
version 1.3

task repro {
    input {
        File file
    }

    command <<<
        ln -s '~{file}' foo
    >>>

    output {
        File out = "foo"
    }
}
```

Create an empty `input.txt` file.

Evaluate the task:

```
$ sprocket run repro.wdl -e test file=input.txt
```

The evaluation fails with:

```
error: failed to evaluate output `out` for task `repro`: file `/home/peterhuene/src/peterhuene/sprocket/runs/repro/2026-01-30_205239130599141/attempts/0/work/foo` does not exist
   ┌─ test.wdl:13:14
   │
13 │         File out = "foo"
   │              ^^^

error: aborting due to evaluation error
```

The symlink exists, but it points at a guest path and not a host path, which is why `sprocket` thinks the file doesn't exist:

```
$ ls -l foo 
lrwxrwxrwx 1 peterhuene peterhuene 28 Jan 30 15:52 foo -> /mnt/task/inputs/6/input.txt
```

**Expected behavior**

For task execution with a local work directory, `sprocket` should "fixup" any symlinks within the task's work directory that point at guest paths (i.e. point at an input file or a path within an input directory) and recreate the links to the corresponding host paths.

An evaluation error should occur if the symlink is _not_ to an input path and does not point to a file within the task's work directory.

**Related Bug**

The planetary transporter should also properly handle symlinks to inputs such that it can skip uploading the output and instead use the original input URL.

### PR DESCRIPTION
**Pull request by peterhuene**
This PR fixes task evaluation such that after a successful evaluation of a task, any symbolic links in a task's work directory that use guest paths are remapped to their corresponding host paths automatically.

Fixes #580.

Before submitting this PR, please make sure:

For external contributors:

- [x] You have read the [contributing guide](https://github.com/stjude-rust-labs/sprocket/blob/main/CONTRIBUTING.md) in its entirety.
- [x] You have not used AI on any parts of this pull request.

For all contributors:

- [x] You have added a few sentences describing the PR here.
- [x] You have added yourself or the appropriate individual as the assignee.
- [x] You have added at least one relevant code reviewer to the PR.
- [x] Your code builds clean without any errors or warnings.
- [x] You have added tests (when appropriate).
- [x] You have added an entry in the CHANGELOG (when appropriate).
- [x] You have updated the README or other documentation to account for these changes (when appropriate).
- [x] You have made a PR to the `next` branch in the [sprocket.bio repository](https://github.com/stjude-rust-labs/sprocket.bio) (when appropriate).

For PRs containing lint rule changes:

- [x] You have updated any and all effected entries within `RULES.md`.
- [x] You have added a test case in `crates/wdl-lint/tests/lints` that covers every
      possible diagnostic emitted for the rule within the file where the rule
      is implemented.

### CODE REVIEW

File: crates/wdl-engine/src/eval/v1/task.rs [hunk 1]
```diff
@@ -1052,6 +1064,121 @@ impl Evaluator {
...
+                    )
+                })?;
+            }
+            #[cfg(windows)]
+            {
+                if symlink_host_path.is_dir() {
+                    std::os::windows::fs::symlink_dir(&symlink_host_path, path).with_context(
+                        || {
+                            format!(
+                                "failed to create directory symlink `{path}` to `{symlink_path}",
```
Comment (claymcleod) [inline crates/wdl-engine/src/eval/v1/task.rs]:
```suggestion
                                "failed to create directory symlink `{path}` to `{symlink_path}`",
```

File: crates/wdl-engine/src/eval/v1/task.rs [hunk 2]
```diff
@@ -1052,6 +1064,121 @@ impl Evaluator {
...
+                    path = path.display()
+                )
+            })?;
+
+            // Recreate the link using the host path
+            #[cfg(unix)]
+            {
+                std::os::unix::fs::symlink(&symlink_host_path, path).with_context(|| {
+                    format!(
+                        "failed to create symlink `{path}` to `{symlink_path}",
```
Comment (claymcleod) [inline crates/wdl-engine/src/eval/v1/task.rs]:
```suggestion
                        "failed to create symlink `{path}` to `{symlink_path}`",
```

File: crates/wdl-engine/src/eval/v1/task.rs [hunk 3]
```diff
@@ -1052,6 +1064,121 @@ impl Evaluator {
...
+                                path = path.display(),
+                                symlink_path = symlink_host_path.display()
+                            )
+                        },
+                    )?;
+                } else {
+                    std::os::windows::fs::symlink_file(&symlink_host_path, path).with_context(
+                        || {
+                            format!(
+                                "failed to create file symlink `{path}` to `{symlink_path}",
```
Comment (claymcleod) [inline crates/wdl-engine/src/eval/v1/task.rs]:
```suggestion
                                "failed to create file symlink `{path}` to `{symlink_path}`",
```

**Review by claymcleod — APPROVED** [review]
