### PR TITLE
fix: add ext rather than set

### LINKED ISSUE #689: apptainer backend - apptainer pull failed because of tag parsing
**Describe the bug**
Using the slurm_apptainer backend.  The workflow I was testing had tasks that used both `docker://google/deepvariant:1.10.0` and `docker://google/deepvariant:1.10.0-gpu`.  The non-gpu task ran first and successfully pulled and cached the image as `out/runs/deepvariant/<run-name>/apptainer-images/docker/google/deepvariant/1.10.sif`.  The gpu task that followed failed to write image to cache.

It looks like it's clipping the `-gpu` suffix from the tag when creating a filename.

**Expected behavior**
Expect that both containers can be written to the cache.

**Terminal Output**

```log
$ sprocket run --verbose workflows/wdl-common-internal/wdl/workflows/deepvariant/deepvariant.wdl inputs/deepvariant.inputs.json
2026-03-05T19:29:59.602190Z  INFO wdl_analysis::graph: parsing of `file:///pbi/flash/wrowell/projects/sprocket_tests/workflows/wdl-common-internal/wdl/workflows/deepvariant/deepvariant.wdl` completed in 529.241µs
2026-03-05T19:29:59.604622Z  INFO wdl_analysis::graph: parsing of `file:///pbi/flash/wrowell/projects/sprocket_tests/workflows/wdl-common-internal/wdl/structs.wdl` completed in 13.19µs
2026-03-05T19:29:59.604704Z  INFO wdl_analysis::queue: analysis of `file:///pbi/flash/wrowell/projects/sprocket_tests/workflows/wdl-common-internal/wdl/structs.wdl` completed in 46.23µs
2026-03-05T19:29:59.605526Z  INFO wdl_analysis::queue: analysis of `file:///pbi/flash/wrowell/projects/sprocket_tests/workflows/wdl-common-internal/wdl/workflows/deepvariant/deepvariant.wdl` completed in 783.76µs
2026-03-05T19:29:59.627653Z  INFO sprocket::commands::run: `./out/runs/deepvariant/2026-03-05_192959613601996` will be used as the execution directory
2026-03-05T19:29:59.975178Z  INFO cloud_copy: using HTTP download cache directory `/home/UNIXHOME/wrowell/.cache/sprocket/downloads`
2026-03-05T19:29:59.975291Z  INFO wdl_engine::cache: using call cache directory `/home/UNIXHOME/wrowell/.cache/sprocket/calls`
2026-03-05T19:30:00.136449Z  INFO wdl_engine::backend::apptainer: spawning `singularity` to pull image `docker://google/deepvariant:1.10.0`
2026-03-05T19:47:30.095714Z  INFO wdl_engine::backend::apptainer: spawning `singularity` to pull image `docker://google/deepvariant:1.10.0-gpu`2026-03-05T19:47:30.122837Z  WARN wdl_engine::backend::apptainer: `singularity pull` failed e=`singularity` failed: exit status: 255: FATAL:   Image file already exists: "<prefix>/out/runs/deepvariant/<run-name>/apptainer-images/docker/google/deepvariant/1.10.sif" - will not overwrite
```

**Screenshots**

**Environment (please complete the following information):**
 - OS: Rocky 9 HPC cluster, slurm 20.02.7, singularity-ce 4.3.1-1.el9
 - Version: sprocket unknown (6088ced85 2026-03-05) dirty 1 modification (#682), WDL v1.2
 - Shell: bash 5.1.8(1)-release
 - Toolchain version: rustc 1.93.1 (01f6ddf75 2026-02-11)

**Additional context**

### PR DESCRIPTION
**Pull request by adthrasher**
Fixes #689. This adds an extension to the local path, rather than replacing the existing extension.

Before submitting this PR, please make sure:

For external contributors:

- [ ] You have read the [contributing guide](https://github.com/stjude-rust-labs/sprocket/blob/main/CONTRIBUTING.md) in its entirety.
- [ ] You have not used AI on any parts of this pull request.
- [ ] You have added a few sentences describing the PR here.
- [ ] Your code builds clean without any errors or warnings.

For all contributors:

- [ ] You have added tests (when appropriate).
- [x] You have added an entry in the CHANGELOG (when appropriate).
- [ ] You have updated the README or other documentation to account for these changes (when appropriate).
- [ ] You have made a PR to the `next` branch in the [sprocket.bio repository](https://github.com/stjude-rust-labs/sprocket.bio) (when appropriate).

For PRs containing lint rule changes:

- [ ] You have updated any and all effected entries within `RULES.md`.
- [ ] You have added a test case in `crates/wdl-lint/tests/lints` that covers every
      possible diagnostic emitted for the rule within the file where the rule
      is implemented.

### CODE REVIEW

File: crates/wdl-engine/src/backend/apptainer.rs [hunk 1]
```diff
@@ -276,7 +276,7 @@ impl ApptainerRuntime {
                 }
             }
 
-            path.set_extension("sif");
+            path.add_extension("sif");
```
Comment (peterhuene) [inline crates/wdl-engine/src/backend/apptainer.rs]: We should check to see if the path already has a `sif` extension, otherwise it'll double it.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=f26dae29233b869eadf9b3cae8cb6d63

Comment (adthrasher) [reply crates/wdl-engine/src/backend/apptainer.rs]: This is always pulling from a registry, right? So the image shouldn't have the `.sif` extension for a local file.

Comment (peterhuene) [reply crates/wdl-engine/src/backend/apptainer.rs]: Oh right, I forgot that we bail above for files. Yeah should be good then.

Comment (adthrasher) [reply crates/wdl-engine/src/backend/apptainer.rs]: I went ahead and wrapped it anyway. I suppose there's nothing stopping someone from naming their container `google/deepvariant:1.9.0-gpu.sif`. So might as well avoid duplicating that if someone does.

**Review by peterhuene — APPROVED** [review]

File: crates/wdl-engine/src/backend/apptainer.rs (hunk 1 above)
Comment (claymcleod) [reply crates/wdl-engine/src/backend/apptainer.rs]: Personally, I think unconditionally adding `.sif` is the right call—even if the tag happens to end in `.sif`, producing `.sif.sif` gives a unique cache path per tag, which is the invariant we care about.

File: crates/wdl-engine/src/backend/apptainer.rs [hunk 2]
```diff
@@ -276,7 +276,11 @@ impl ApptainerRuntime {
                 }
             }
 
-            path.set_extension("sif");
+            if let Some(ext) = path.extension()
+                && ext != "sif"
+            {
+                path.add_extension("sif");
+            }
```
Comment (claymcleod) [inline crates/wdl-engine/src/backend/apptainer.rs]: When a tag has no dots (e.g., `latest`, `v2`, `focal`), `path.extension()` returns `None` and the `if let` doesn't match—so `.sif` is never appended. The cache path becomes `.../latest` instead of `.../latest.sif`.

Per [the documentation for `add_extension()`](https://doc.rust-lang.org/std/path/struct.PathBuf.html#method.add_extension), the method appends unconditionally (returning `false` only when `file_name` is `None`, which can't happen here). My preference would be to just call `path.add_extension("sif")` unconditionally, but if you'd like to deduplicate the `.sif` extension:

```suggestion
            if path.extension().is_none_or(|ext| ext != "sif") {
                path.add_extension("sif");
            }
```

**Comment by claymcleod** [comment]
Since @williamrowell is waiting on this and it has multiple approvals, I'm going to go ahead and merge this in.
