### PR TITLE
fix: prevent the loss of error context from Sprocket commands.

### LINKED ISSUE #181: `check` errors while attempting to recurse my `runs/` directory
Very unhelpful error messaging:
```console
$ RUST_BACKTRACE=1 cargo run -- check ../workflows/
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.47s
     Running `target/debug/sprocket check ../workflows/`
error: error parsing ignorefile with basename `.sprocketignore`

Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
   2: std::backtrace::Backtrace::create
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/backtrace.rs:331:13
   3: anyhow::kind::Adhoc::new
             at /Users/afrantz/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anyhow-1.0.99/src/backtrace.rs:27:14
   4: sprocket::commands::check::check::{{closure}}
             at ./src/commands/check.rs:313:13
   5: sprocket::inner::{{closure}}
             at ./src/main.rs:89:77
   6: sprocket::main::{{closure}}
             at ./src/main.rs:108:29
   7: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /Users/afrantz/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/future.rs:124:9
   8: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/afrantz/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/park.rs:285:71
   9: tokio::task::coop::with_budget
             at /Users/afrantz/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/coop/mod.rs:167:5
  10: tokio::task::coop::budget
             at /Users/afrantz/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/task/coop/mod.rs:133:5
  11: tokio::runtime::park::CachedParkThread::block_on
             at /Users/afrantz/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/park.rs:285:31
  12: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /Users/afrantz/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/context/blocking.rs:66:14
  13: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /Users/afrantz/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/multi_thread/mod.rs:87:22
  14: tokio::runtime::context::runtime::enter_runtime
             at /Users/afrantz/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/context/runtime.rs:65:16
  15: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /Users/afrantz/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/scheduler/multi_thread/mod.rs:86:9
  16: tokio::runtime::runtime::Runtime::block_on_inner
             at /Users/afrantz/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/runtime.rs:358:50
  17: tokio::runtime::runtime::Runtime::block_on
             at /Users/afrantz/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.47.1/src/runtime/runtime.rs:328:18
  18: sprocket::main
             at ./src/main.rs:108:35
  19: core::ops::function::FnOnce::call_once
             at /Users/afrantz/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  20: std::sys::backtrace::__rust_begin_short_backtrace
             at /Users/afrantz/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:152:18
  21: std::rt::lang_start::{{closure}}
             at /Users/afrantz/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:206:18
  22: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/ops/function.rs:284:21
  23: std::panicking::catch_unwind::do_call
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:589:40
  24: std::panicking::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:552:19
  25: std::panic::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panic.rs:359:14
  26: std::rt::lang_start_internal::{{closure}}
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/rt.rs:175:24
  27: std::panicking::catch_unwind::do_call
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:589:40
  28: std::panicking::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:552:19
  29: std::panic::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panic.rs:359:14
  30: std::rt::lang_start_internal
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/rt.rs:171:5
  31: std::rt::lang_start
             at /Users/afrantz/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:205:5
  32: _main
```
The error is not actually related to my `.sprocketignore` at all. I have a very well-populated `runs/` directory as I've been doing a lot of `sprocket run` calls, and something in there is causing an error. This is confirmed by adding `runs/` to my `.sprocketignore` which prevents the error.

The error occurs while trying to walk the directory - https://github.com/stjude-rust-labs/wdl/blob/main/wdl-analysis/src/analyzer.rs#L436

I was also able to fix this with
```console
$ cat runs/.sprocketignore
*
```
Maybe we should have Sprocket write an ignorefile for any directories it creates?

### PR DESCRIPTION
**Pull request by peterhuene**
This PR fixes Sprocket commands such that they don't erase error context by creating a new error derived from an existing error.

The commands now return a `CommandResult` which has an error that can be a single `anyhow::Error` or multiple shared errors from analysis. Previously it was returning `anyhow::Result`, which meant the shared errors had to convert to an owned `anyhow::Error`, which causes the loss of context.

Fixes #181.

Before submitting this PR, please make sure:

For external contributors:

- [x] You have read the [contributing guide](https://github.com/stjude-rust-labs/sprocket/blob/main/CONTRIBUTING.md) in its entirety.
- [x] You have not used AI on any parts of this pull request.

For all contributors:

- [x] You have added a few sentences describing the PR here.
- [x] You have added yourself or the appropriate individual as the assignee.
- [x] You have added at least one relevant code reviewer to the PR.
- [x] Your code builds clean without any errors or warnings.
- [x] You have added tests (when appropriate).
- [x] You have added an entry in the CHANGELOG (when appropriate).
- [x] You have updated the README or other documentation to account for these changes (when appropriate).
- [x] You have either (a) made a PR to the `next` branch in the sprocket.bio repository [if you are a Sprocket team member] or (b) have suggested any changes you _think_ need to be made to sprocket.bio in the description of your PR [if you are an external contributor].

For PRs containing lint rule changes:

- [x] You have updated any and all effected entries within `RULES.md`.
- [x] You have added a test case in `crates/wdl-lint/tests/lints` that covers every
      possible diagnostic emitted for the rule within the file where the rule
      is implemented.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -130,6 +134,8 @@ async fn inner() -> anyhow::Result<()> {
 /// The Sprocket command line entrypoint.
 pub async fn sprocket_main() {
     if let Err(e) = inner().await {
+        // Only display the first error if multiple errors were encountered
+        let e = e.first();
```
Comment (claymcleod) [inline src/lib.rs]: Now that we've gone to the trouble to capture multiple errors all the way to this point, do we want to consider just displaying all of the errors?
