### PR TITLE
fix: fixes the parsing of literal inputs, outputs, and hints

### LINKED ISSUE #517: Sprocket doesn't pass the `input_hint_task` conformance test in WDL v1.2.1.
This test is as follows:

```wdl
version 1.2

struct Person {
  String name
  File? cv
}

task input_hint {
  input {
    Person person
  }

  command <<<
  if ~{defined(person.cv)}; then
    grep "WDL" ~{person.cv}
  fi
  >>>
  
  output {
    Array[String] experience = read_lines(stdout())
  }

  hints {
    inputs: input {
      person.name: hints {
        min_length: 3
      },
      person.cv: hints {
        localization_optional: true
      }
    }
    outputs: output {
      experience: hints {
        max_length: 5
      }
    }
  }
}
```

We don't parse the `input`, `hints, `and `output` blocks correctly.

### PR DESCRIPTION
**Pull request by claymcleod**
See #517 for more details on the issue.

* Also fixes clamping of `max_cpu` and `max_memory` in the Docker backend.

The `test_hints_task` conformance test now passes.

Closes #517.

Before submitting this PR, please make sure:

For external contributors:

- [ ] You have read the [contributing guide](https://github.com/stjude-rust-labs/sprocket/blob/main/CONTRIBUTING.md) in its entirety.
- [ ] You have not used AI on any parts of this pull request.

For all contributors:

- [x] You have added a few sentences describing the PR here.
- [x] You have added yourself or the appropriate individual as the assignee.
- [x] You have added at least one relevant code reviewer to the PR.
- [x] Your code builds clean without any errors or warnings.
- [x] You have added tests (when appropriate).
- [x] You have added an entry in the CHANGELOG (when appropriate).
- [x] You have updated the README or other documentation to account for these changes (when appropriate).
- [x] You have either (a) made a PR to the `next` branch in the sprocket.bio repository [if you are a Sprocket team member] or (b) have suggested any changes you _think_ need to be made to sprocket.bio in the description of your PR [if you are an external contributor].

For PRs containing lint rule changes:

- [ ] You have updated any and all effected entries within `RULES.md`.
- [ ] You have added a test case in `crates/wdl-lint/tests/lints` that covers every
      possible diagnostic emitted for the rule within the file where the rule
      is implemented.

### CODE REVIEW

File: crates/wdl-engine/src/backend/docker.rs [hunk 1]
```diff
@@ -452,8 +452,11 @@ impl TaskExecutionBackend for DockerBackend {
         if let TaskResourceLimitBehavior::TryWithMax = self.config.task.memory_limit_behavior {
             memory = std::cmp::min(memory, self.max_memory);
         }
-        let max_cpu = max_cpu(hints);
-        let max_memory = max_memory(hints)?.map(|i| i as u64);
+        // NOTE: in the Docker backend, we clamp the `max_cpu` and `max_memory`
+        // to what is reported by the backend, as the Docker daemon does not
+        // respond gracefully to over-subscribing these.
+        let max_cpu = max_cpu(hints).map(|c| c.min(self.max_cpu as f64));
+        let max_memory = max_memory(hints)?.map(|i| (i as u64).min(self.max_memory));
```
Comment (adthrasher) [inline crates/wdl-engine/src/backend/docker.rs:459]: Is this correct? Above, we clamp the _minimum_ cpu and memory to the maximum available from Docker. The _max_ values are just hints that the process can use _no more than_ the specified amount of memory.

Comment (claymcleod) [reply crates/wdl-engine/src/backend/docker.rs:459]: You are correct in the definitions.

Ultimately, this `max_cpu` gets passed as the `cpu_limit` ([link](https://github.com/stjude-rust-labs/sprocket/blob/467ee53e04ad05533a00419270b2f9cbe1db3cc3/crates/wdl-engine/src/backend/docker.rs#L233)) to `crankshaft`, which, in turn, is used to reserve the CPU limit in Docker ([link](https://github.com/stjude-rust-labs/crankshaft/blob/a7da3c003e02fde4b18d4f90823ed04dc999df26/crankshaft-engine/src/task/resources.rs#L211-L220)). The `HostConfig`'s `nano_cpus` describes itself as a "CPU quota" ([link](https://docs.rs/bollard/latest/bollard/models/struct.HostConfig.html#structfield.nano_cpus)), so this seems like the right choice between `cpu` and `cpu_limit`, though it means that, for the Docker backend only, we need to cap these to what is available on the resource.

**Review by peterhuene — APPROVED** [review]
