### PR TITLE
fix: print diagnostics for `sprocket run`.

### LINKED ISSUE #108: Unhelpful error message when missing version statement
When the `version` statement is missing at the top, the error message is unhelpful.

```wdl
task hello {
  String name

  command {
    echo 'Hello ${name}!'
  }
  output {
    File response = stdout()
  }
}

workflow test {
  call hello
}
```

```shell
$ cargo run --release run hello.wdl --overwrite
# error: no workflow was found in `file:///Users/cmcleod/Desktop/hello.wdl`; either specify a document with a workflow or use the `-n` option to refer to a specific task or workflow by name
```

This should instead complain about this missing `version` statement.

### LINKED ISSUE #109: Unhelpful error message when diagnostics exist
The following occurs when trying to run this workflow.

```wdl
version 1.2

task hello {
  String name

  command {
    echo 'Hello ${name}!'
  }
  output {
    File response = stdout()
  }
}

workflow test {
  call hello
}
```

```shell
$ cargo run --release run hello.wdl --overwrite
# error: cannot evaluate a document with errors
```

This requires an extra call to `sprocket check` to see the related diagnostics. We should just print the diagnostics straight from `sprocket run`.

### PR DESCRIPTION
**Pull request by peterhuene**
This commit fixes a failure to print diagnostics after the analysis performed by `sprocket run`.

If the diagnostics contain any errors, the command aborts before evaluation is attempted.

Fixes #108.
Fixes #109.

Before submitting this PR, please make sure:

For external contributors:

- [x] You have read the `wdl` crates' [CONTRIBUTING](https://github.com/stjude-rust-labs/wdl/blob/main/CONTRIBUTING.md) guide in its entirety.
- [x] You have not used AI on any parts of this pull request.

For all contributors:

- [x] You have added a few sentences describing the PR here.
- [x] You have added yourself or the appropriate individual as the assignee.
- [x] You have added at least one relevant code reviewer to the PR.
- [x] Your code builds clean without any errors or warnings.
- [x] You have added tests (when appropriate).
- [x] You have added an entry in the CHANGELOG (when appropriate).
- [x] You have updated the README or other documentation to account for these changes (when appropriate).

### CODE REVIEW

File: src/commands/run.rs [hunk 1]
```diff
@@ -209,16 +211,49 @@ pub async fn run(args: Args) -> Result<()> {
...
+    let mut errors = 0;
+    for result in &results {
+        let diagnostics = result.document().diagnostics();
+        if !diagnostics.is_empty() {
+            let path = result.document().path().to_string();
+            let source = result.document().root().text().to_string();
+
+            errors += diagnostics
+                .iter()
+                .filter(|d| d.severity() == Severity::Error)
```
Comment (a-frantz) [inline src/commands/run.rs:232]: we frequently do this, and I wonder if we should have a "shortcut". OOS for this PR, just a thought.

**Review by a-frantz — APPROVED** [review]

**Review by claymcleod — APPROVED** [review]

File: src/commands/run.rs (hunk 1 above)
Comment (peterhuene) [reply src/commands/run.rs:232]: Yeah, we can probably enhance the `AnalysisResults` type for the common functionality, which exists in the `wdl` crates (didn't want to touch those with this fix, though).
