### PR TITLE
fix: create ignorefiles in `runs/` instead of `runs/<entrypoint>/`

### LINKED ISSUE #479: better automatic `.sprocketignore` placement
#471 added a needed fix that makes directories in `runs/` ignored by Sprocket. However it places the generated file at `<runs>/<entrypoint>/.sprocketignore`. It would be preferable to instead place the generated file at `<runs>/.sprocketignore`.

### PR DESCRIPTION
**Pull request by nikhil-nari**
_Describe the problem or feature in addition to a link to the issues._

Creates `.sprocketignore` in `/runs` main directory instead of `runs/entrypoint/`
Fixes #479 

Before submitting this PR, please make sure:

For external contributors:

- [x] You have read the [contributing guide](https://github.com/stjude-rust-labs/sprocket/blob/main/CONTRIBUTING.md) in its entirety.
- [x] You have not used AI on any parts of this pull request.

For all contributors:

- [x] You have added a few sentences describing the PR here.
- [x] You have added yourself or the appropriate individual as the assignee.
- [x] You have added at least one relevant code reviewer to the PR.
- [x] Your code builds clean without any errors or warnings.
- [x] You have added tests (when appropriate).
- [x] You have added an entry in the CHANGELOG (when appropriate).
- [x] You have updated the README or other documentation to account for these changes (when appropriate).
- [x] You have either (a) made a PR to the `next` branch in the sprocket.bio repository [if you are a Sprocket team member] or (b) have suggested any changes you _think_ need to be made to sprocket.bio in the description of your PR [if you are an external contributor].

For PRs containing lint rule changes:

- [x] You have updated any and all effected entries within `RULES.md`.
- [x] You have added a test case in `crates/wdl-lint/tests/lints` that covers every
      possible diagnostic emitted for the rule within the file where the rule
      is implemented.

### CODE REVIEW

File: src/commands/run.rs [hunk 1]
```diff
@@ -435,17 +435,16 @@ async fn progress(
...
     let ignore_path = root.join(crate::IGNORE_FILENAME);
     if !ignore_path.exists() {
         let ignorefile = File::create(&ignore_path)
             .with_context(|| format!("creating ignorefile: `{}`", ignore_path.display()))?;
         writeln!(&ignorefile, "*")
             .with_context(|| format!("failed to write ignorefile: {} ", ignore_path.display()))?;
     }
+    let root = root.join(entrypoint);
+    std::fs::create_dir_all(&root)
+        .with_context(|| format!("failed to create directory: `{dir}`", dir = root.display()))?;
```
Comment (a-frantz) [inline src/commands/run.rs:454]: from the CI logs:
```
 2 test(s) failed:
run/compare-coerced: result from `tests/cli/run/compare-coerced/stderr` is not as expected:
after normalization:
Diff < left / right > :
>error: creating ignorefile: `runs/.sprocketignore`
>
>Caused by:
>    No such file or directory (os error 2)
>

run/ensure-absolute-inputs: result from `tests/cli/run/ensure-absolute-inputs/stderr` is not as expected:
after normalization:
Diff < left / right > :
>error: creating ignorefile: `runs/.sprocketignore`
>
>Caused by:
>    No such file or directory (os error 2)
>

error: test failed, to rerun pass `-p sprocket --test cli`

Caused by:
  process didn't exit successfully: `/home/runner/work/sprocket/sprocket/target/debug/deps/cli-6f28913c6495fca6` (exit status: 1)
```
With your change here, we try to create the ignorefile before the `runs/` directory is created which is what's causing the failure. The order of operations you have needs to change a bit, but this is close!

File: src/commands/run.rs [hunk 2]
```diff
@@ -435,17 +435,16 @@ async fn progress(
...
-        .with_context(|| format!("failed to create directory: `{dir}`", dir = root.display()))?;
-
     let ignore_path = root.join(crate::IGNORE_FILENAME);
     if !ignore_path.exists() {
         let ignorefile = File::create(&ignore_path)
             .with_context(|| format!("creating ignorefile: `{}`", ignore_path.display()))?;
         writeln!(&ignorefile, "*")
             .with_context(|| format!("failed to write ignorefile: {} ", ignore_path.display()))?;
     }
+    let root = root.join(entrypoint);
```
Comment (a-frantz) [inline src/commands/run.rs]: instead of re-using the variable name `root` here, we should make it more descriptive so this is clearer. Maybe:
```suggestion
    let entrypoint_root = root.join(entrypoint);
```

File: CHANGELOG.md [hunk 3]
```diff
@@ -39,6 +39,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 * Removed the `wdl-cli` crate, absorbing its code into the `sprocket` library
   crate in preparation for future refactoring ([#450](https://github.com/stjude-rust-labs/sprocket/pull/450)).
 * Apptainer-based backends now store converted container images within each run directory, rather than in a user-specified directory ([#463](https://github.com/stjude-rust-labs/sprocket/pull/463)).
+* Running `sprocket run` now writes a `.sprocketignore` file directly to the runs/ directory ([#481](https://github.com/stjude-rust-labs/sprocket/pull/481)).
```
Comment (a-frantz) [inline CHANGELOG.md]:
```suggestion
* `sprocket run` now writes a `.sprocketignore` file directly to the `runs/` directory instead of the `runs/<entrypoint>/` directory ([#481](https://github.com/stjude-rust-labs/sprocket/pull/481)).
```

**Review by a-frantz — CHANGES_REQUESTED** [review]
This is close! Nice work, thanks for this

**Comment by nikhil-nari** [comment]
> This is close! Nice work, thanks for this
Thanks for pointing out the issue.

**Review by a-frantz — APPROVED** [review]
Looks great! Appreciate this :+1:
Our review policy requires two sign offs before a merge. I'll ping someone to give it another set of eyes!

**Review by peterhuene — APPROVED** [review]
