### PR TITLE
fix(wdl-analysis): error on struct literals in 1.0 documents

### LINKED ISSUE #596: Sprocket supports struct literal expressions in 1.0 documents when it should not
**Describe the bug**

It appears that struct literal expressions were [introduced in WDL 1.1](https://github.com/openwdl/wdl/pull/297).

Sprocket should error on the use of such expressions within a 1.0 document.

For example:

```wdl
version 1.0

struct Foo {
    Int bar
}

workflow repro {
    Foo foo = Foo {
        bar: 0
    }
}
```

The above should produce an error for the struct literal expression used in the declaration of `foo`.

### PR DESCRIPTION
**Pull request by Serial-ATA**
closes #596

Before submitting this PR, please make sure:

For external contributors:

- [x] You have read the [contributing guide](https://github.com/stjude-rust-labs/sprocket/blob/main/CONTRIBUTING.md) in its entirety.
- [x] You have not used AI on any parts of this pull request.

For all contributors:

- [x] You have added a few sentences describing the PR here.
- [x] You have added yourself or the appropriate individual as the assignee.
- [x] You have added at least one relevant code reviewer to the PR.
- [x] Your code builds clean without any errors or warnings.
- [x] You have added tests (when appropriate).
- [x] You have added an entry in the CHANGELOG (when appropriate).
- [x] You have updated the README or other documentation to account for these changes (when appropriate).
- [x] You have made a PR to the `next` branch in the [sprocket.bio repository](https://github.com/stjude-rust-labs/sprocket.bio) (when appropriate).

For PRs containing lint rule changes:

- [x] You have updated any and all effected entries within `RULES.md`.
- [x] You have added a test case in `crates/wdl-lint/tests/lints` that covers every
      possible diagnostic emitted for the rule within the file where the rule
      is implemented.

### CODE REVIEW

File: crates/wdl-analysis/src/validation/version.rs [hunk 1]
```diff
@@ -274,6 +279,12 @@ impl Visitor for VersionVisitor {
             {
                 diagnostics.add(directory_type_requirement(ty.span()));
             }
+
+            if let expr @ v1::Expr::Literal(v1::LiteralExpr::Struct(_)) = decl.expr()
+                && version < SupportedVersion::V1(V1::One)
```
Comment (peterhuene) [inline crates/wdl-analysis/src/validation/version.rs]: Could we compare the version before the call to `decl.expr()` as that will walk the CST? The version comparison is cheap.

File: crates/wdl-analysis/src/validation/version.rs [hunk 2]
```diff
@@ -55,6 +55,11 @@ fn input_keyword_requirement(span: Span) -> Diagnostic {
         .with_fix("add an `input` keyword followed by a colon before any call inputs")
 }
 
+/// Creates a "struct literal requirement" diagnostic.
+fn struct_literal_requirement(span: Span) -> Diagnostic {
+    Diagnostic::error("use of a struct literal requires WDL version 1.1").with_highlight(span)
```
Comment (peterhuene) [inline crates/wdl-analysis/src/validation/version.rs]:
```suggestion
    Diagnostic::error("use of a struct literal requires WDL version 1.1 or later").with_highlight(span)
```

File: crates/wdl-analysis/tests/validation/struct-literal-1.0/source.wdl [hunk 3]
```diff
@@ -0,0 +1,12 @@
...
+
+struct Foo {
+    Int bar
+}
+
+workflow repro {
+    Foo foo = Foo {
+        bar: 0
+    }
+}
```
Comment (claymcleod) [inline crates/wdl-analysis/tests/validation/struct-literal-1.0/source.wdl]: nit: missing trailing newline at end of file.

**Review by claymcleod — CHANGES_REQUESTED** [review]
Please address Peter's suggestions above, plus one minor nit below.

File: crates/wdl-analysis/src/validation/version.rs [hunk 4]
```diff
@@ -274,6 +280,12 @@ impl Visitor for VersionVisitor {
             {
                 diagnostics.add(directory_type_requirement(ty.span()));
             }
+
+            if version < SupportedVersion::V1(V1::One)
+                && let expr @ v1::Expr::Literal(v1::LiteralExpr::Struct(_)) = decl.expr()
```
Comment (a-frantz) [inline crates/wdl-analysis/src/validation/version.rs:291]: I don't think I've ever seen this syntax before 😅 had to look it up. TIL!

**Review by claymcleod — APPROVED** [review]
Thanks!
