### PR TITLE
fix: capture and print trailing comments

### LINKED ISSUE #235: bug: trailing full line comments are excluded from formatting
**Describe the bug**

A WDL document ending with a trailing inline comment is formatted correctly, but if that comment occurs on a line by itself it is excluded from formatting and gets removed from the output.

**Expected behavior**

All comments should be respected.

**Terminal Output**

```bash
$ cat trailing_inline.wdl
version 1.2

task foo {
}  # this is fine
$ sprocket format --check trailing_inline.wdl
checking `trailing_inline.wdl`
`trailing_inline.wdl` is formatted correctly
$ cat trailing_full_line.wdl
version 1.2

task foo {
}
# this is excluded from format results
$ sprocket format --check trailing_full_line.wdl
checking `trailing_full_line.wdl`
Diff < left / right > :
 version 1.2

 task foo {
 }
<# this is excluded from format results

error: aborting due to previous 1 diagnostic
$ sprocket --version
sprocket 0.13.0 (2025-05-28)
```

**Additional context**

This case is caused by the trivia model used by the `wdl-format` crate. For formatting purposes, each AST token may have "preceding trivia" and/or "inline trivia"; "succeeding trivia" is never considered by the formatting logic, which is what causes this bug.

Preceding trivia is captured by this function - https://github.com/stjude-rust-labs/wdl/blob/002918a67e40bd6cab72fd9530320e1bd948331e/wdl-grammar/src/tree.rs#L727
Inline trivia is captured by this function - https://github.com/stjude-rust-labs/wdl/blob/002918a67e40bd6cab72fd9530320e1bd948331e/wdl-grammar/src/tree.rs#L791

and there is an existing `succeeding_trivia()` function, but it's dead code not used anywhere - https://github.com/stjude-rust-labs/wdl/blob/002918a67e40bd6cab72fd9530320e1bd948331e/wdl-grammar/src/tree.rs#L771

### PR DESCRIPTION
**Pull request by a-frantz**
_Describe the problem or feature in addition to a link to the issues._

closes #235 

this explicitly only looks for "trailing comments" when formatting an entire AST. I think this is _probably_ the best approach? It at least avoids having to make any larger refactors or changes to the trivia model. However, I'm open to the possibility that the model I settled on for trivia (every comment is either preceding or inline) is flawed and should be revisited.

Before submitting this PR, please make sure:

For external contributors:

- [ ] You have read the [contributing guide](https://github.com/stjude-rust-labs/sprocket/blob/main/CONTRIBUTING.md) in its entirety.
- [ ] You have not used AI on any parts of this pull request.

For all contributors:

- [x] You have added a few sentences describing the PR here.
- [x] You have added yourself or the appropriate individual as the assignee.
- [x] You have added at least one relevant code reviewer to the PR.
- [x] Your code builds clean without any errors or warnings.
- [x] You have added tests (when appropriate).
- [x] You have added an entry in the CHANGELOG (when appropriate).
- [x] You have updated the README or other documentation to account for these changes (when appropriate).
- [x] You have either (a) made a PR to the `next` branch in the sprocket.bio repository [if you are a Sprocket team member] or (b) have suggested any changes you _think_ need to be made to sprocket.bio in the description of your PR [if you are an external contributor].

For PRs containing lint rule changes:

- [ ] You have updated any and all effected entries within `RULES.md`.
- [ ] You have added a test case in `crates/wdl-lint/tests/lints` that covers every
      possible diagnostic emitted for the rule within the file where the rule
      is implemented.

### CODE REVIEW

File: crates/wdl-format/src/token/pre.rs [hunk 1]
```diff
@@ -241,14 +241,4 @@ impl TokenStream<PreToken> {
     pub fn push_literal(&mut self, value: String, kind: SyntaxKind) {
         self.0.push(PreToken::Literal(Rc::new(value), kind));
     }
-
-    /// Returns the kind of the last literal token in the stream.
-    pub fn last_literal_kind(&self) -> Option<SyntaxKind> {
```
Comment (a-frantz) [inline crates/wdl-format/src/token/pre.rs:246]: this was dead code and it doesn't look logically sound to me anyway. I don't think this warrants a "removed" entry in the changelog, but logging here in case anyone disagrees

File: crates/wdl-format/src/token/post.rs [hunk 2]
```diff
@@ -237,15 +237,12 @@ impl Postprocessor {
...
-        // TODO: bug where trailing trivia is not processed
-        // https://github.com/stjude-rust-labs/wdl/issues/497
-
         output
     }
 
     /// Takes a step of a [`PreToken`] stream and processes the appropriate
     /// [`PostToken`]s.
-    pub fn step(
+    fn step(
```
Comment (a-frantz) [inline crates/wdl-format/src/token/post.rs:245]: don't think this needs a changelog entry, but logging here for discussion if anyone disagrees. (It never should have been made pub in the first place)

File: crates/wdl-format/src/v1.rs [hunk 3]
```diff
@@ -67,16 +80,75 @@ pub fn format_ast(element: &FormatElement, stream: &mut TokenStream<PreToken>) {
...
+        for comment in comments {
+            stream.push(PreToken::Trivia(crate::Trivia::Comment(
+                crate::Comment::Preceding(Rc::new(comment.text().into())),
+            )));
+            stream.push(PreToken::LineEnd);
+        }
+    }
+}
+
+/// Pushes any trailing comments at the end of a WDL document to the stream.
```
Comment (a-frantz) [inline crates/wdl-format/src/v1.rs]:
```suggestion
/// Finds any trailing comments at the end of a WDL document.
```

File: crates/wdl-format/src/token/pre.rs (hunk 1 above)
Comment (acfoltzer) [reply crates/wdl-format/src/token/pre.rs:246]: I'm fine with these changes given that we're the only known users of this crate at the moment, but on my eternally-growing todo list is for us to come up with a more explicit policy for changelogs. I don't think the current approach where it's basically a log of PRs is very helpful in practice when we have the commit history, but deciding what does and doesn't deserve a changelog entry isn't entirely obvious.

File: crates/wdl-format/src/v1.rs [hunk 4]
```diff
@@ -67,16 +80,75 @@ pub fn format_ast(element: &FormatElement, stream: &mut TokenStream<PreToken>) {
...
+        }
+    }
+}
+
+/// Finds any trailing comments at the end of a WDL document.
+///
+/// Trailing comments are unhandled as they don't fit neatly into the trivia
+/// model used by this crate. [`crate::Comment`]s can only be "proceeding" or
+/// "inline", but non-inline comments at the end of a WDL document
+/// have no following element to proceed. This will find any such comments and
```
Comment (acfoltzer) [inline crates/wdl-format/src/v1.rs]:
```suggestion
/// model used by this crate. [`crate::Comment`]s can only be "preceding" or
/// "inline", but non-inline comments at the end of a WDL document
/// have no following element to precede. This will find any such comments and
```
