### PR TITLE
fix(wdl-doc): preserve doc comment line breaks

### LINKED ISSUE #651: Fenced code blocks not working in preamble for `sprocket dev doc`
Hey Sprocket folks! Just wanted to bring a `doc` issue we noticed recently, apologies if this has already been identified elsewhere in another issue, feel free to close if that's the case.

**Describe the bug**

Fenced code blocks in `##` preamble comments don't render correctly in `sprocket dev doc` output. The opening code fence never closes, so all subsequent preamble content gets swallowed into the code block.

This works correctly in v0.18.0 but is broken in v0.21.1.

**Expected behavior**

After stripping `## `, the markdown fences (`` ``` ``) should open and close code blocks normally, with subsequent content rendering outside the block.

**Terminal Output**

Given a WDL file with this preamble:

```
## # My Module
##
## ```wdl
## import "example.wdl" as example
## ```
##
## ## Next Section
##
## Some text here.

version 1.0
```

Running:
```bash
sprocket dev doc .
```

The "Next Section" heading and text render inside the code block instead of after it.

**Environment:**
 - OS: macOS (Darwin 24.5.0)
 - Version: Works in v0.18.0, broken in v0.21.1
 - Shell: zsh

**Additional context**

We prepend README content as `##` preamble comments to WDL files during our docs build. The code fences in those READMEs become `` ## ```wdl `` / `` ## ``` `` in the preamble, which v0.18.0 handles correctly.

### PR DESCRIPTION
**Pull request by a-frantz**
_Describe the problem or feature in addition to a link to the issues._

fixes #651 

Before submitting this PR, please make sure:

For external contributors:

- [ ] You have read the [contributing guide](https://github.com/stjude-rust-labs/sprocket/blob/main/CONTRIBUTING.md) in its entirety.
- [ ] You have not used AI on any parts of this pull request.

For all contributors:

- [ ] You have added a few sentences describing the PR here.
- [ ] You have added yourself or the appropriate individual as the assignee.
- [ ] You have added at least one relevant code reviewer to the PR.
- [ ] Your code builds clean without any errors or warnings.
- [ ] You have added tests (when appropriate).
- [ ] You have added an entry in the CHANGELOG (when appropriate).
- [ ] You have updated the README or other documentation to account for these changes (when appropriate).
- [ ] You have made a PR to the `next` branch in the [sprocket.bio repository](https://github.com/stjude-rust-labs/sprocket.bio) (when appropriate).

For PRs containing lint rule changes:

- [ ] You have updated any and all effected entries within `RULES.md`.
- [ ] You have added a test case in `crates/wdl-lint/tests/lints` that covers every
      possible diagnostic emitted for the rule within the file where the rule
      is implemented.

### CODE REVIEW

File: crates/wdl-doc/src/meta.rs [hunk 1]
```diff
@@ -468,12 +465,15 @@ pub(crate) fn doc_comments(comments: impl IntoIterator<Item = Comment>) -> MetaM
...
         DESCRIPTION_KEY.to_string(),
-        MetaMapValueSource::Comment(paragraphs.remove(0).to_string()),
+        // SAFETY: if paragraphs were empty, we would have returned early
+        MetaMapValueSource::Comment(paragraphs.next().unwrap().to_string()),
     );
 
-    let help = paragraphs.into_iter().fold(String::new(), |mut acc, p| {
+    let help = paragraphs.fold(String::new(), |mut acc, p| {
         if !acc.is_empty() {
             acc.push('\n');
```
Comment (claymcleod) [inline crates/wdl-doc/src/meta.rs]: With the `Paragraph::Display` change from `" "` to `"\n"`, lines within a paragraph are now separated by `\n`. This means the single `\n` between paragraphs no longer creates a visual boundary—consider using `"\n\n"` here.

```suggestion
            acc.push_str("\n\n");
```
