### PR TITLE
fix(wdl-analysis): error on implicit input bindings in 1.0 documents

### LINKED ISSUE #292: Implicit binding of inputs is allowed in 1.0 docs
This goes against the spec, which says implicit bindings are only allowed in >=v1.1.

Discovered in stjude-rust-labs/wdl#244 

Confirmed by this test:
```
$ cat tmp.wdl
version 1.0

workflow test {
    input {
        String foo
    }

    call bar { input: foo }
}

task bar {
    input {
        String foo
    }

    command <<<>>>
}
$ sprocket check tmp.wdl
warning[UnusedCall]: unused call `bar`
  ┌─ tmp.wdl:8:10
  │
8 │     call bar { input: foo }
  │          ^^^

warning[UnusedInput]: unused input `foo`
   ┌─ tmp.wdl:13:16
   │
13 │         String foo
   │                ^^^
```

### PR DESCRIPTION
**Pull request by Serial-ATA**
closes #292

Before submitting this PR, please make sure:

For external contributors:

- [x] You have read the [contributing guide](https://github.com/stjude-rust-labs/sprocket/blob/main/CONTRIBUTING.md) in its entirety.
- [x] You have not used AI on any parts of this pull request.

For all contributors:

- [x] You have added a few sentences describing the PR here.
- [x] You have added yourself or the appropriate individual as the assignee.
- [x] You have added at least one relevant code reviewer to the PR.
- [x] Your code builds clean without any errors or warnings.
- [x] You have added tests (when appropriate).
- [x] You have added an entry in the CHANGELOG (when appropriate).
- [x] You have updated the README or other documentation to account for these changes (when appropriate).
- [x] You have made a PR to the `next` branch in the [sprocket.bio repository](https://github.com/stjude-rust-labs/sprocket.bio) (when appropriate).

For PRs containing lint rule changes:

- [x] You have updated any and all effected entries within `RULES.md`.
- [x] You have added a test case in `crates/wdl-lint/tests/lints` that covers every
      possible diagnostic emitted for the rule within the file where the rule
      is implemented.

### CODE REVIEW

File: crates/wdl-analysis/src/validation/version.rs [hunk 1]
```diff
@@ -48,6 +48,12 @@ fn directory_type_requirement(span: Span) -> Diagnostic {
     Diagnostic::error("use of the `Directory` type requires WDL version 1.2").with_highlight(span)
 }
 
+/// Creates an "implicit binding" requirement diagnostic.
+fn implicit_binding_requirement(span: Span) -> Diagnostic {
+    Diagnostic::error("use of implicit input bindings requires WDL version 1.1")
```
Comment (peterhuene) [inline crates/wdl-analysis/src/validation/version.rs]:
```suggestion
    Diagnostic::error("use of implicit input bindings requires WDL version 1.1 or later")
```
