### PR TITLE
fix: remap symlinks before saving call cache entry.

### LINKED ISSUE #684: Guest symlink updating can break cache checking
**Describe the bug**
The functionality in #580 and #621 introduces rewriting of symlinks in the container outputs. This updates the timestamp for the symlink. The caching should check the timestamp of the underlying file, but this doesn't seem be happening.

For St. Jude users, the context is this Slack thread: https://stjude.slack.com/archives/C065YHBRNBS/p1772724498213549

**Expected behavior**
Sprocket should rewrite the symlinks prior to calculating the digests for the cache. It also needs to resolve symlinks and check the timestamp on the underlying target.

### PR DESCRIPTION
**Pull request by peterhuene**
This PR ensures that remapping of local work directory symlinks occurs before saving the call cache entry.

By doing so, the digest of the work directory is calculated with updated symlinks rather than potentially broken symlinks.

Fixes #684.

Before submitting this PR, please make sure:

For external contributors:

- [x] You have read the [contributing guide](https://github.com/stjude-rust-labs/sprocket/blob/main/CONTRIBUTING.md) in its entirety.
- [x] You have not used AI on any parts of this pull request.
- [x] You have added a few sentences describing the PR here.
- [x] Your code builds clean without any errors or warnings.

For all contributors:

- [x] You have added tests (when appropriate).
- [x] You have added an entry in the CHANGELOG (when appropriate).
- [x] You have updated the README or other documentation to account for these changes (when appropriate).
- [x] You have made a PR to the `next` branch in the [sprocket.bio repository](https://github.com/stjude-rust-labs/sprocket.bio) (when appropriate).

For PRs containing lint rule changes:

- [x] You have updated any and all effected entries within `RULES.md`.
- [x] You have added a test case in `crates/wdl-lint/tests/lints` that covers every
      possible diagnostic emitted for the rule within the file where the rule
      is implemented.

### CODE REVIEW

File: crates/wdl-engine/src/eval/v1/task.rs
Comment (adthrasher) [inline crates/wdl-engine/src/eval/v1/task.rs:1120]: This gets triggered on a rerun of the cached task.

File: crates/wdl-engine/src/eval/v1/task.rs [hunk 1]
```diff
@@ -956,6 +956,16 @@ impl Evaluator {
                 continue;
             }
 
+            // Remap any guest symbolic links to the corresponding host paths
+            // This must occur *before* we put the result in the cache to ensure consistent
+            // work directory digesting
+            if let Err(e) = self.remap_links(&state, &result.work_dir) {
```
Comment (adthrasher) [inline crates/wdl-engine/src/eval/v1/task.rs]:
```suggestion
            if !cached && let Err(e) = self.remap_links(&state, &result.work_dir) {
```
